### PR TITLE
perf: faster equals with Object.is short circuit

### PR DESCRIPTION
**Pull request by agriffis**
It seems like R.equals does a lot of work even if passed the same reference, for example:

```js
const x = {/* big structure */}
R.equals(x, x) // does deep compare
```

Is there a reason that it doesn't have an `Object.is` short-circuit?

### CODE REVIEW

**Comment by selfrefactor** [comment]
Thanks for this MR
As I am working on other things, new release will be made sometime next week.

**Comment by agriffis** [comment]
Thank you! I'm looking forward to the release.

**Comment by agriffis** [comment]
@selfrefactor Are you still planning on a release soon?

**Comment by selfrefactor** [comment]
released with 9.1.1; txs for reminder

**Comment by agriffis** [comment]
Thanks! I put a comment on #726 and #727 because I think there might be a problem, but otherwise, I'm looking forward to this in rambdax since that's what I actually use :sweat_smile:

**Pull request merged**
