### PR TITLE
fix: regexp replacer can be a function

### PR DESCRIPTION
**Pull request by agriffis**

### CODE REVIEW

**Comment by selfrefactor** [comment]
Thanks for opening this up. I will need to have a closer look before merging.

**Comment by agriffis** [comment]
No problem. I wasn't sure the big overload for `ReplacerFn` was the best, but :man_shrugging:

**Comment by selfrefactor** [comment]
I will release this with 7.6.0, sorry for the delay.

**Comment by selfrefactor** [comment]
After giving proper look at these changes, I will have to decline them. I don't want to deviate much further from Ramda.replace method. I hope you do understand and I appreciate your effort.

**Comment by selfrefactor** [comment]
thanks for the clarification. I was a bit uncertain as no unit test was added. I didn't realize that string.replace can be called with a function. I will try to add some unit tests as they are also needed in the context of the suggested change.

**Comment by selfrefactor** [comment]
I approve this MR and it will be released as part of `8.0` version

**Pull request merged**
