### PR TITLE
Add `partiallyApplyNamed`.

### PR DESCRIPTION
**Pull request by VoidNoire**
To be frank, I don't really know TypeScript, so any TypeScript-related changes that I (should've) made are most likely wrong, and I'm also not sure if the name is fine, so please let me know what other changes I should make to correct any errors.

### CODE REVIEW

**Comment by selfrefactor** [comment]
I think that for the name, we should go with the same name as the source, e.g. `namedCurry`.

You caught a typo in `CONTRIBUTING.md`, but I am unsure that your other changes are on purpose.

I'd ask you to write a short explanation inside `files/index.d.ts` for the new method. Or you can provide simple example usage, as it can be a substitute for the explanation.

I will take care for Typescript definitions and tests. 

Last thing - you didn't get my Rambdax explanation, so I will try to explain with more words. Rambdax hosts all methods that are not part of `Ramda` API. In the case of your new method, Ramda doesn't have similar function, so we export such methods via Rambdax.

**Comment by VoidNoire** [comment]
> I think that for the name, we should go with the same name as the source, e.g. `namedCurry`.

To be honest, I'm not sure if the source got it correct either, but fair enough. I think I've renamed the relevant files and occurences, but I might've missed some, so please let me know if I did.

> You caught a typo in `CONTRIBUTING.md`, but I am unsure that your other changes are on purpose.

Yeah, so when I tried to follow the old instructions in it, I kept running into issues. I changed it to include the steps I took that made it work. As for the change in `README.md`, I don't recall manually editing it. Maybe it was caused by some automated process? But I'm not sure.

In any case, I can revert those changes if you like?

> I'd ask you to write a short explanation inside `files/index.d.ts` for the new method. Or you can provide simple example usage, as it can be a substitute for the explanation.

Sure thing. I've added some so please let me know if they're adequate, or if they still require some changes.

> I will take care for Typescript definitions and tests.
> 
> Last thing - you didn't get my Rambdax explanation, so I will try to explain with more words. Rambdax hosts all methods that are not part of `Ramda` API. In the case of your new method, Ramda doesn't have similar function, so we export such methods via Rambdax.

Thanks for trying to explain it a bit better, although, to be honest, I still don't quite understand what you mean when you say "export such methods via Rambdax". I tried looking for differences between `Rambdax`-exclusive functions and standard `Rambda` functions, but I couldn't figure it out. So, my apologies about this, but could you please let me know what this means in terms of what changes I actually have to make such that the new function exports methods via `Rambdax`?

For what it's worth, it might also be a good idea to include this information in the `CONTRIBUTING.md` file, to aid future contributors.

**Comment by selfrefactor** [comment]
I will take another look into the changes in `CONTRIBUTING.md` file. You don't need to revert them. Also, I agree that this document could be improved.

As for the misunderstanding - indeed there is one. I was talking about `Ramda` library, which `Rambda` tries to emulate. The new method is not part of Ramda, so it cannot be part of Rambda, so it goes to Rambdax(which is Rambda + additional methods). 

You are right about changes in README.md - they are effect from build scripts.

For the naming, I might have a better suggestion, once I finish its Typescript definitions and tests, but for me the naming is not a big issue, as I expect troubles in writing TS definitions.

**Comment by VoidNoire** [comment]
> As for the misunderstanding - indeed there is one. I was talking about `Ramda` library, which `Rambda` tries to emulate. The new method is not part of Ramda, so it cannot be part of Rambda, so it goes to Rambdax(which is Rambda + additional methods).

Ah I think I understand you now. Did you mean I should open the PR for the https://github.com/selfrefactor/rambdax repository instead of this one? If so, should I close this one?

> For the naming, I might have a better suggestion, once I finish its Typescript definitions and tests, but for me the naming is not a big issue, as I expect troubles in writing TS definitions.

I'll leave it up to you to decide on the name as I don't really have a good suggestion for it. And thanks for handling the TypeScript-related tasks. I would've had no idea where to begin on those otherwise hah.

**Comment by selfrefactor** [comment]
Rambdax repo now is only a build output. Even if the change will not reflect `Rambda`, you correctly opened PR here, as here live both packages. I will approve this PR and I will let you know if I have problems. Also, I will tag you once the method is exported.

**Comment by VoidNoire** [comment]
Sure thing. Sorry for all the misunderstanding and thanks for your patience.

**Comment by VoidNoire** [comment]
Ah man this is embarrassing, but it seems I've made an error when renaming the files. I renamed them "curryNamed", whereas the function's been renamed to `namedCurry`. Sorry about that.

**Comment by selfrefactor** [comment]
Yes, I saw that and still made the merge, as I this is easy to fix._

**Comment by selfrefactor** [comment]
@VoidNoire I just dig into your code as yesterday I had other focus. I find that the method is confusing and has little value. I did remove it, but your changes to `CONTRIBUTING.md` are intact. Sorry about that, but I do that to my own methods as well and I provide a quote from Rambdax's changelog:

```

Deprecate the following methods:

- `R.promiseAllObject` - because `R.produce` serves the same purpose
- `R.composed` - because `R.piped` makes more sense, when we want to pass the input at the start of the function
- `R.defaultToStrict` - confusing logic
- `R.findInObject` - overestimated importance
- `R.headObject` - overestimated importance
- `R.includesType` - overestimated importance
- `R.inject` - confusing logic
- `R.isAttach` - confusing logic
- `R.mergeRight` - overestimated importance
- `R.opposite` - overestimated importance
- `R.otherwise` - overestimated importance
- `R.pushUniq` - overestimated importance
- `R.resolve` - overestimated importance
- `R.s` - overestimated importance
- `R.toggle` - overestimated importance
- `R.uuid` - not suitable
- `R.whenAsync` - overestimated importance
```

**Pull request merged**
