### PR TITLE
Imrove R.head

### PR DESCRIPTION
**Pull request by sschneider-ihre-pvs**

### CODE REVIEW

**Comment by selfrefactor** [comment]
Thanks for the MR, but since it is changing typings, can you provide test either in the test file or as a comment here?

**Comment by selfrefactor** [comment]
I decided that next version will be major so this MR will be soon merged.

**Comment by sschneider-ihre-pvs** [comment]
Well, that was my attempt to cover the list part since the typing in the example was only for string and not for string[]

**Comment by selfrefactor** [comment]
I am trying to improve this MR with proper testing but I fail to nail it. 
I intend to test also these solutions:

https://github.com/millsp/ts-toolbelt/blob/master/sources/List/List.ts
https://github.com/sindresorhus/type-fest/blob/main/source/last-array-element.d.ts

**Comment by sschneider-ihre-pvs** [comment]
Maybe try the guy that hangout in the totally typescript discord :D this is a really tricky one

**Comment by selfrefactor** [comment]
I was finally satisfied with https://github.com/sindresorhus/type-fest/blob/main/source/last-array-element.d.ts

I will close the issue, but I will ping you from here once 8.0 is released

**Comment by sschneider-ihre-pvs** [comment]
https://discord.gg/8S5ujhfTB3

**Comment by selfrefactor** [comment]
8.0 version is released and improvement of R.head are there

**Pull request closed without merging**
