### PR TITLE
chore: add pipe typespec

### PR DESCRIPTION
**Pull request by yordis**

### CODE REVIEW

**Comment by selfrefactor** [comment]
Sorry for taking so long. MR is approved and it will become active once `6.10.0` is published. I will write you once it is done.

**Comment by selfrefactor** [comment]
We have an issue with the new typings @yordis as more complex tests are failing.

This is passing Ramda test:

```
import {dissoc, pipe, identity} from 'ramda'

interface Input {
  a: string,
  b: string,
}
const obj: Input = {
  a: 'foo',
  b: 'bar',
}
interface Output {
  a: string,
}

describe('R.dissoc', () => {
  it('within R.pipe', () => {
    const result = pipe<Input, Input, Output>(identity, dissoc('b'))(obj)

    result // $ExpectType Output
  })
})
```

I fail to make such test pass with the new typings. Maybe I am missing something, so if you can help, that would be nice. Otherwise, I will have to revert to old typings, even though they are so complex and take too much space.

**Comment by yordis** [comment]
Oh btw `pipe<Input, Input, Output>` you no longer pass any `<Input, Input, Output>` since the function is smart enough ... so remove that part from it.

**Comment by selfrefactor** [comment]
I don't see how that helps as without it, I cannot force a type safety.

**Comment by yordis** [comment]
You enforce in the proper area thou

```tsx
const result = pipe(
  identity,
  dissoc<Input>('b') // do it here
)(obj)
```

Or keep improving the other functions as well.

**Comment by selfrefactor** [comment]
I will try your suggestion and get back to you.

**Comment by selfrefactor** [comment]
It didn't work as well as I hoped. Please see the tests, where `composex` is your suggested types. As you can see, at that point, we'll have to stick with the current types:

```
it('with native filter', () => {
    const result = compose(
      (list: number[]) => list.filter(x => x > 2),
      list => {
        list // $ExpectType number[]
        return list
      },
      map(add(1))
    )([1, 2, 3])

    const resultx = composex(
      (list: number[]) => list.filter(x => x > 2),
      list => {
        list // $ExpectType any
        return list
      },
      map(add(1))
    )([1, 2, 3])

    result // $ExpectType number[]
    resultx // $ExpectType number[]
  })

  it('with native filter 2', () => {
    const result = compose<Array<number>, Array<number>, Array<number>, Array<number>>(
      (list) => {
        list // $ExpectType number[]
        return list.filter(x => x > 2)
      },
      list => {
        list // $ExpectType number[]
        return list
      },
      map(add(1))
    )([1, 2, 3])

    const resultx = composex(
      // $ExpectError
      (list) => list.filter(x => x > 2),
      list => {
        list // $ExpectType any
        return list
      },
      map(add(1))
    )([1, 2, 3])

    result // $ExpectType number[]
    resultx // $ExpectType any
  })
```

**Pull request merged**
