### PR TITLE
 feat@identical

### PR DESCRIPTION
**Pull request by ku8ar**
+ fix ramdaMissing script

BTW It will take some time. Weather too good, sand in Black Sea is too warm ;)

### CODE REVIEW

**Comment by selfrefactor** [comment]
Great stuff.
Where are you at Black Sea? Is it Bulgaria?

**Comment by ku8ar** [comment]
@selfrefactor no, second side. Batumi ;)

**Comment by selfrefactor** [comment]
Sounds nice. By all means take the most of what Black Sea can offer. BTW can you share you plans for next methods, as I am cannot promise that I will want all of the easy to create Ramda methods.

For example `R.and(true, true);` is one such example. I really feel that seeing

```
const a = compose(
  and(head(list)),
  last
)(list)
```

would make a normal person mad.

The other case:

```
if(and(x,y)) fn()
```

is also confusing. 

I opened an issue where we can keep track on these methods and reason about them: #218

**Comment by selfrefactor** [comment]
Deployed with `2.13.0`

**Comment by ku8ar** [comment]
@selfrefactor Currently I think about rewriting all functions that are used in the project in which I work. Mainly from groups: list, object.

**Pull request merged**
