### PR TITLE
Increase benchmarks correctness

### PR DESCRIPTION
**Pull request by selfrefactor**
In relation to https://github.com/selfrefactor/rambda/issues/475

This PR allows support complex benchmarks. Initially only one method's benchmarks are created(R.find). 

Roadmap:

- Redo all current benchmarks to be in the new format
- Remove old type of benchmarks
- Change documentation pipeline to support the new format

### CODE REVIEW

**Comment by selfrefactor** [comment]
@farwayer Can you give a feedback on this PR?

**Comment by selfrefactor** [comment]
Thank you for the fast reply.

Regarding point 1 - I used `fast` and `slow` as temporary placeholders which are subject to change. Different methods has different corner cases and maybe after writing benchmarks for several more methods, then it will be more clearer. The word `empty` is too generic for this context. I am tempted to add more words to describe the mode of the benchmark suite. Maybe something like `const rambdaWithLargeList = ...`. In this case `empty` would be much more appropriate.

As for point 2 - I tried initially to solve it with several files instead of one, but it wasn't a step in the right direction. Still, it is possible, but it will require additional build step and I try to contain the complexity of the whole build process.

So, should I proceed with merging this PR?

**Comment by farwayer** [comment]
Sure, it is your project :wink: I'm just helping a bit

**Comment by selfrefactor** [comment]
There was one more reason to keep 1 benchmark file per method - currently benchmarks are included in the README.md and if we had more than 1 benchmark file, that would require a complicated fix to documentation pipeline. I was open to explore even considering this drawback, but it just didn't seem right when I tested it. I can add you as contributor, as this will allow you to review and approve PRs. Should I send you an invite?

**Pull request merged**
