### PR TITLE
method@applySpec

### PR DESCRIPTION
**Pull request by synthet1c**
Hey Dejan,

Here is the code for applySpec.

Same deal as last time. Two tests failing "build" and "typings".

Methods, tests, benchmarks, docs finished but no typescript definitions.

This is a useful function because you can give it a spec object with a bunch of curried functions for the properties, then pass it arguments, once all the arguments are supplied it will execute the curried functions of the spec object recursively and return you a new object with the result of calling each function on each property.

One caveat for this is that if someone uses the `R.curry` method of rambda `applySpec` won't know the arity of the calling function since `R.curry` uses `(...args)` to catch all the arguments. I looked into adding `R.curryN` and replacing `R.curry` but I can't get it to perform faster than ramda. My best attempt was half as fast as ramda, I'm not sure how you feel about that.

If you need help with the typings let me know.

Cheers,

Andrew

### CODE REVIEW

**Comment by selfrefactor** [comment]
Good work as usual :+1: 

I had conflicts in Readme.md and if you can share your description of the method, that would be great as I had to resolve them in my favour.

**Comment by synthet1c** [comment]
Hey,

Here is the markdown from the raw file.

I'm not sure about the type signature. I really need to learn typescript...

#### applySpec

Returns a curried function with the same arity as the longest function in the spec object (max 5 arity). 
Arguments will be applied to the spec methods recursively. This is useful for changing the shape of a json object

> applySpec({ x: Function }, T): T

```
const getMetrics = R.applySpec({
  sum: R.add,
  nested: { mul: R.multiply }
});
getMetrics(2, 4); // => { sum: 6, nested: { mul: 8 } }

const spec = {
    name: R.path('user', 'firstname')
}
const json = {
    user: {
        firstname: 'barry'
    }
}
applySpec(spec, json) // => { user: 'barry' }
```

[Source](https://github.com/selfrefactor/rambda/tree/master/src/applySpec.js)

**Comment by selfrefactor** [comment]
@synthet1c I just ran R.applySpec with Ramda tests and there are three failing. You will notice them in Rambda's applySpec.spec.js file as the only skipped tests.

The middle one is most curious of them and I would like your input on that. The other two tests can be included in expected differences list, but I will need your confirmation on that.

**Comment by synthet1c** [comment]
I'll take a look

**Comment by synthet1c** [comment]
Looks like, it's meant to work on arrays. I will need to refactor the function to allow either Arrays or Objects. I kind of rushed this one as you said you wanted to make a release and I really want this method.

I could quite easily refactor it to use R.map as that handles both arrays and objects, but we might lose the speed benefit of rambda over ramda.

I'll investigate hopefully tonight

**Comment by selfrefactor** [comment]
I don't mind using R.map if that solves it.

**Comment by selfrefactor** [comment]
@synthet1c Any progress on the failing tests?

I am done with big change in terms of how Typescript definitions are exported and I will use this pretext to deprecate `R.partialCurry`. It will be a major bump and I'd like to include your method if it is ready.

**Comment by selfrefactor** [comment]
Another update - I manage to hack a solution for that test that worried me, so I will go forward and publish the method with the next bump. Thank you again for the good work.

**Comment by synthet1c** [comment]
Hey Dejan,

Sorry I had to focus on work this week and didn't get time to spend
implementing the fix, Glad you got it sorted.

Regards,

Andrew

**Comment by synthet1c** [comment]
Hey Dejan,

I fixed up applySpec and commited to my pull request, all the tests pass
accept nAry, but that's because it doesn't yet exist. I only ran `yarn
build` ran the tests and committed.

Cheers,

Andrew

**Comment by selfrefactor** [comment]
Hi Andrew,

I am glad you manage to fix the failing tests, but I am not able to see the latest commits. Are you about to open a new PR?

**Comment by synthet1c** [comment]
I committed it to the old one. I can extract the code into a new one if you
like.

**Pull request merged**
