### PR TITLE
Method@converge

### PR DESCRIPTION
**Pull request by synthet1c**
Hey Dejan,

Here is another 2 methods that I need `converge` and `curryN`.

Usual parts, code, specs, benchmarks, docs, no typescript types and the docs are not compiled.

Unfortunately I couldn't get `curryN` to run faster than ramda, but it's a negligible decrease in performance.

I should also mention that the previous methods I have provided don't have the sourcecode and test results links in the docs, I'm not sure how to add them.

Cheers,

Andrew

### CODE REVIEW

**Comment by synthet1c** [comment]
Actually I found out why converge was slower, it's because I labeled the tests wrong. Rambda is actually faster! Can you swap them and rebuild the benchmark before you publish? Or I can cancel this pull request and make a new one if that's easier.
```
const converge = [
  {
    label : 'Rambda', // should be Ramda
    fn    : () => {
      const fn = Ramda.converge(Ramda.multiply, [
        Ramda.add(1),
        Ramda.add(3)
      ]);

      fn(4)
    },
  },
  {
    label : 'Ramda', // should be Rambda
    fn    : () => {
      const fn = R.converge(R.multiply, [
        R.add(1),
        R.add(3)
      ]);

      fn(4)
    },
  },
]
```

**Comment by selfrefactor** [comment]
I am adding both methods and I will bump the version tomorrow. As for the missing scripts for some of the required deploy steps. I am working on it and there should be better development experience after those changes.

**Comment by selfrefactor** [comment]
Also, I will not include documentation and typings for these 2 methods, as they will be added afterwards, when my other branch is merged. Still, there will be available for import and use as long as you don't use Typescript or Flex. For the typing we'll have to wait a bit.

**Comment by synthet1c** [comment]
Awesome, thanks for that :-)

**Comment by selfrefactor** [comment]
Hi, Andrew

Just released `5.1.0` with the above changes. Thanks again.

**Pull request merged**
