### PR TITLE
feat: lte

### PR DESCRIPTION
**Pull request by ilteoood**
Implementation of the lte utility

### CODE REVIEW

**Comment by selfrefactor** [comment]
txs for the PR, but please look at the changes - there are many related to whitespace which shouldn't be included.
You can remove them or I will take the changes and include them manually.

**Comment by ilteoood** [comment]
I think are related to my vscode settings, which uses Unix new line formatting.
Is it a real problem? Are just spaces in comments 🤔

**Comment by selfrefactor** [comment]
It makes it hard to read, which for me is enough reason. Also, I have to be careful with git history of files/index.tsx as it is too important file.

**Comment by selfrefactor** [comment]
I am approving this MR as a reward for the time you spent on it, but also because you found issue with the method declaration.

Actually, the method exists, it is just not exported due to RegEx issue.

**Pull request merged**
