### PR TITLE
Feat@method obj of

### PR DESCRIPTION
**Pull request by synthet1c**
Hey Dejan,

Added a new method objOf following the CONTRIBUTIONS.md guide, I tried to run `yarn run out` but it failed because it's not windows compatible and was missing ramdax and ramda-docs repos, so I'll have to leave it for you to build. Tests are passing and Types are correct.

On the types not sure if it should accept only a string key or both a string or number key, both are valid.

Also when running `yarn build` it no longer compiles probably because the function is not exported from `/rambda.js`. I can't find any examples of pulling in the code from `/source/*.js`, Do I need to create the same function in `/src/*.js` ?

Cheers,

Andrew

### CODE REVIEW

**Comment by selfrefactor** [comment]
Thanks for the PR. Will get back to you with feedback.

**Comment by synthet1c** [comment]
When linked with `yarn link` it couldn't detect the method until I created `src/objOf.js` added it to `/rambda.js` and added the typings to `/index.d.ts`, initially I added the typings where the CONTRIBUTIONS readme said.

Here is the error from `yarn run out`. I don't have ramdax or rambda-docs installed in the same parent folder. I needed to use cross-env to set the system variables in the package.json.

```
$ yarn run out
yarn run v1.22.4
$ cd ../rambda-scripts&&yarn populate:docs&&cd ../rambda-scripts&&yarn populate:readme
$ cross-env RAMBDA_SCRIPTS_MODE=populate:docs jest src/apply-rambda-scripts.spec.ts
 FAIL  src/apply-rambda-scripts.spec.ts (29.54 s)
  × happy (11 ms)

  ● happy

    There are invalid paths docsBase,docsDir

      27 |
      28 |   if (Object.keys(validPaths).length !== Object.keys(PATHS).length) {
    > 29 |     throw new Error(`There are invalid paths ${wrongPaths}`)
         |           ^
      30 |   }
      31 |   if(!WITH_RAMBDAX) return
      32 |

      at validatePaths (src/apply-rambda-scripts.ts:29:11)
      at Object.<anonymous> (src/apply-rambda-scripts.ts:42:3)
      at step (src/apply-rambda-scripts.ts:33:23)
      at Object.next (src/apply-rambda-scripts.ts:14:53)
      at src/apply-rambda-scripts.ts:8:71
      at Object.<anonymous>.__awaiter (src/apply-rambda-scripts.ts:4:12)
      at Object.applyRambdaScripts (src/apply-rambda-scripts.ts:75:12)
      at src/apply-rambda-scripts.spec.ts:13:9
      at step (src/apply-rambda-scripts.spec.ts:33:23)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        31.451 s
Ran all test suites matching /src\\apply-rambda-scripts.spec.ts/i.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Cheers,

Anderw

**Comment by selfrefactor** [comment]
Did you had the latest `rambda-docs` repo, as fix was applied recently?

**Comment by synthet1c** [comment]
I just created the repo's for rambda-docs, ramdax, rambda-scripts and rambda all in a single folder.

ramdax, rambda-scripts & rambda all installed fine, however, rambda-docs did not install and had an error. I searched for hjson-js in the repo, but it could not be found.

Not sure why it's trying to install from git, there is nothing in the package.json, there is no postinstall script that triggers any processes.

```
fount@DESKTOP-1LLN6T9 MINGW64 /g/projects/rambda/rambda-docs (master)
$ yarn
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
warning Pattern ["colors@latest"] is trying to unpack in the same destination "C:\\Users\\fount\\AppData\\Local\\Yarn\\Cache\\v6\\npm-colors-1.4.0-integrity\\node_modules\\colors" as pattern ["colors@^1.4.0","colors@^1.4.0"]. This cou

ld result in non-deterministic behavior, skipping.
warning Pattern ["object-assign@latest"] is trying to unpack in the same destination "C:\\Users\\fount\\AppData\\Local\\Yarn\\Cache\\v6\\npm-object-assign-4.1.1-integrity\\node_modules\\object-assign" as pattern ["object-assign@^4.1.1

","object-assign@^4.0.1","object-assign@^4.1.1","object-assign@^4"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["send@latest"] is trying to unpack in the same destination "C:\\Users\\fount\\AppData\\Local\\Yarn\\Cache\\v6\\npm-send-0.17.1-integrity\\node_modules\\send" as pattern ["send@0.17.1","send@0.17.1"]. This could result

 in non-deterministic behavior, skipping.
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads https://github.com/selfrefactor/hjson-js
Directory: G:\projects\rambda\rambda-docs
Output:
remote: Repository not found.
fatal: repository 'https://github.com/selfrefactor/hjson-js/' not found
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by selfrefactor** [comment]
This is expected as I deprecated hjson in Rambda and I removed the fork from my repos. The origin of the error is old version of `helpers-fn` in `rambda-docs/package.json`.

It should work with latest `rambda` and `rambda-docs`(`rambdax` and `rambda-docs` are optional and in your case unneeded).

**Comment by selfrefactor** [comment]
I made some fixes in this commit https://github.com/selfrefactor/rambda/commit/b0fe1eaf3ac98cd804f15e46d3967eafc48b9db2

You can check it if you want to. My main feedback is that the tests should have tested bad inputs. Also, if you can share if your `yarn out` is working with latest `rambda-scripts`.

P.S. I know that there is error in the commit in regards to index.d.ts example and this will be fixed

**Comment by synthet1c** [comment]
Thanks for the feedback!

Unfortunately, the build still is not working. I have pulled, rambda-scripts and rambda-docs, updated my local master to match the upstream branch, installed everything with yarn but it's failing in the same spot.

The path for the rambda-docs/assets is missing from ramda-scripts/src/constants.ts:18. 

Because of this I attempted to build the rambda-docs but it's still missing hjson-js.

```bash
fount@DESKTOP-1LLN6T9 MINGW64 /g/projects/rambda/rambda-docs (master)
$ yarn
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
warning Pattern ["colors@latest"] is trying to unpack in the same destination "C:\\Users\\fount\\AppData\\Local\\Yarn\\Cache\\v6\\npm-colors-1.4.0-integrity\\node_modules\\colors" as pattern ["colors@^1.4.0","colors@^1.4.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["object-assign@latest"] is trying to unpack in the same destination "C:\\Users\\fount\\AppData\\Local\\Yarn\\Cache\\v6\\npm-object-assign-4.1.1-integrity\\node_modules\\object-assign" as pattern ["object-assign@^4.1.1","object-assign@^4.0.1","object-assign@^4.1.1","object-assign@^4"]. This could result

 in non-deterministic behavior, skipping.
warning Pattern ["send@latest"] is trying to unpack in the same destination "C:\\Users\\fount\\AppData\\Local\\Yarn\\Cache\\v6\\npm-send-0.17.1-integrity\\node_modules\\send" as pattern ["send@0.17.1","send@0.17.1"]. This could result in non-deterministic behavior, skipping.
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads https://github.com/selfrefactor/hjson-js
Directory: G:\projects\rambda\rambda-docs
Output:
remote: Repository not found.
fatal: repository 'https://github.com/selfrefactor/hjson-js/' not found
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I found hjson-js in the yarn.lock file of the rambda-scripts repo as a dependency of the helpers-fn package
* rambda-scripts/scripts/lint-ts-files/yarn.lock:1036
* rambda-scripts/scripts/lint-ts-files/yarn.lock:1043

```yaml
helpers-fn@1.3.2:
  version "1.3.2"
  resolved "https://registry.yarnpkg.com/helpers-fn/-/helpers-fn-1.3.2.tgz#8d3be184f3b2e957b40adcd4d2c5cc853598257f"
  integrity sha512-6weEc65YcrM7UPaNT0yiaSaPi2ODUxTFzNvuTz5RgCinZSmosrmnxvDZNRIwUKsGeqAY/K9Oufrhpqy/NDevrw==
  dependencies:
    benny "3.6.15"
    boxen "4.2.0"
    cfonts "2.8.6"
    chalk "4.1.0"
    env-fn "2.1.1"
    fdir "4.1.0"
    fs-extra "9.0.1"
    gradient-string "1.2.0"
    hjson-js "https://github.com/selfrefactor/hjson-js#1.1.2"
    log-symbols "4.0.0"
    node-os-utils "1.3.2"
    q-i "2.0.1"
    rambdax "7.0.1"
    string-fn "3.1.0"

"hjson-js@git+https://github.com/selfrefactor/hjson-js.git#1.1.2":
  version "3.2.1"
  resolved "git+https://github.com/selfrefactor/hjson-js.git#4b2cc987be6b603967888719f18c56c0118907d4"
  dependencies:
    rambdax "7.0.1"
```

**Comment by selfrefactor** [comment]
Thanks for the info as I needed it. I will write again, once I made a new release with R.objOf.

**Pull request merged**
