### PR TITLE
fix: accept readonly array in reduce function

### PR DESCRIPTION
**Pull request by G07cha**
It would make it compatible with both readonly and mutable arrays

### CODE REVIEW

**Comment by selfrefactor** [comment]
As Rambda overwrites `ts-toolbelt`, these changes should be applied within the `scripts/dynamic-ts-toolbelt` folder. I can use this PR as specification and apply your changes, or you can do that yourself - I will leave the choice to you.

**Comment by G07cha** [comment]
Thanks for review @selfrefactor! I actually realized that I was trying to fix typings for wrong function, typings for `pipe` are fine but `reduce` has mutable array as expected type for `list` argument. I've updated my PR and added test for it in `consume-typings` script, let me know if there is anything else missing.

**Comment by G07cha** [comment]
Thanks for review @selfrefactor! I actually realized that I was trying to fix typings for wrong function, typings for `pipe` are fine but `reduce` has mutable array as expected type for `list` argument. I've updated my PR and added test for it in `consume-typings` script, let me know if there is anything else missing.

**Comment by selfrefactor** [comment]
Thank you @G07cha for your fast reply. So, no it seems that we don't need to edit `ts-toolbelt` which makes things easier. Still, you need to edit `files/index.d.ts` and run `yarn out`. This is all described in CONTRIBUTION.md file.

**Comment by G07cha** [comment]
Indeed, my bad, updated PR

**Comment by selfrefactor** [comment]
Will be published with WIP version `6.3.0` within one week.

**Pull request merged**
