### PR TITLE
fix: takeLastWhile didn't stop on its own

### PR DESCRIPTION
**Pull request by agriffis**
The test which supposedly tested this depended on the predicate returning false eventually.

### CODE REVIEW

**Comment by agriffis** [comment]
Actually I'll push another commit to clean up the approach for dropWhile, takeWhile, dropLastWhile, takeLastWhile

**Comment by selfrefactor** [comment]
this looks bad from my side. I will approve and take a closer look later but if you are right, I have to merge with `Thank you` and no questions.

**Comment by selfrefactor** [comment]
BTW, you don't need new commit for the other methods as I will check them myself.

**Comment by agriffis** [comment]
Whenever you can make a release with this fix in particular, that would be appreciated. It's a bit awkward to work around it!

**Pull request merged**
