### PR TITLE
Lenses

### PR DESCRIPTION
**Pull request by synthet1c**
Hey Selfrefactor,

Please review this pull request to add lenses to rambda.

I have built all the files I could.
* `yarn test`
* `yarn build`
* `yarn docs`

I'm on windows so added cross-env to set environment variables, and I use phpstorm so added .idea to the gitignore. Everything else was related to the new methods, their tests, documentation and benchmarking.

I don't use typescript so didn't attempt to put in typings, if you need help with it let me know, I can probably figure it out or explain to you how lenses work so you can do it.

Not sure if you need to do anything else.

Love the library and the idea to simplify ramda so it runs faster and leaner without all the bloat. I look forward to helping you add more functionality to it.

Cheers,

Andrew

### CODE REVIEW

**Comment by synthet1c** [comment]
It's probably too early to merge this, it still has an issue with the tests not passing due to the build and typings tasks.

**Comment by selfrefactor** [comment]
I will work on the issues and the failing tests. Afterwards, we are ready for release.

**Comment by synthet1c** [comment]
Great,

Can you let me know what went wrong with the build when you figure it out?
It wasn't clear as the package was able to build without problems, but the
'build' task still failed. I spent a bit of time hunting it down but
couldn't find the cause.

Cheers

**Comment by selfrefactor** [comment]
There were failing tests in master and that could be one of the reasons, but of course I will inform you more about that.

**Pull request merged**
